### ISSUE TITLE
Pressing GUI buttons Freezes and Crashes game

### ISSUE THREAD

**Issue by AlisterGontineac** [Lucxjo/Kontrolo#17]
The game keeps freezing, followed by a crash when using the Kontrolo GUI. Any of the options cause this to happen. Been using Kontrolo for a long time now, and never encountered this issue.
Oh..huh, I guess I didn't notice, there isn't a 1.19.2 file. Could be the issue I guess. Sorry
https://paste.ee/p/AXR4D
[New Paste 1.txt](https://github.com/Lucxjo/Kontrolo-Fabric/files/10173293/New.Paste.1.txt)

**Comment by Lucxjo** [comment]
Using 1.19.2 shouldn't be the issue, but I'm unsure as to whether I've verified it against the game version.

I'll take a look at this sometime soon but I'm somewhat busy at the moment. 

Is the game only crashing on the game mode buttons or does it do it with all? Have you tried the Custom GUI? Does that do the same?

**Comment by AlisterGontineac** [comment]
I thought it was only the game mode buttons, but then I tried every other button, and it freezes and crashes with those as well. 
Take your time, I'm in no rush. Probably some mod conflict. I just thought maybe I would bring it to your attention, and at some point maybe it could help someone.

**Comment by Lucxjo** [comment]
An update is now available that fixes this. The problem was down to a change in the Fabric APIs. The update has only been tested on Minecraft 1.19.3 so let me know if it does/doesn't work with 1.19.2 and I'll release an update that has been built against that specific version
